sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 781204


  alioss:
    endpoint: oss-cn-guangzhou.aliyuncs.com
    access-key-id: LTAI5t9JgG1YmVr5p9phNboW
    access-key-secret: ${ALIYUN_ACCESS_KEY_SECRET}
    bucket-name: web-tlias19200411523

  redis:
    host: localhost
    port: 6379
    password: 781204
    database: 0
